import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
// Bundle the demo into separate JS and CSS files.
// JS: compiled IIFE outputted to crates/blitz-quick-desktop/src/gen/bundle.js
// CSS: generated by UnoCSS and outputted to crates/blitz-quick-desktop/src/gen/bundle.css
import { fileURLToPath } from "node:url";
import { createGenerator, presetUno } from "unocss";
import { defineConfig, type Plugin } from "vite";
import solid from "vite-plugin-solid";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const SRC_DIR = resolve(__dirname, "src");

function walkSrc(dir: string, out: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) walkSrc(p, out);
    else if (/\.(tsx?|jsx?)$/.test(name)) out.push(p);
  }
  return out;
}

function unocssSeparated(): Plugin {
  let unoPromise: ReturnType<typeof createGenerator> | null = null;
  const getUno = () =>
    (unoPromise ??= createGenerator({ presets: [presetUno()] }));
  return {
    name: "unocss-separated",
    async writeBundle() {
      const uno = await getUno();
      const code = walkSrc(SRC_DIR)
        .map((f) => readFileSync(f, "utf8"))
        .join("\n");
      const { css } = await uno.generate(code);
      // UnoCSS presetWind's preflight only emits `--un-*` variables, NOT the
      // Tailwind reset (`*,*::before,*::after{box-sizing:border-box}` — that
      // lives in the separate `@unocss/reset-css` package we don't import). The
      // blitz UA stylesheet sets `box-sizing: border-box` only on `table`, so
      // without this reset any `width:100%` element with padding (e.g. the app
      // root's `p-8`) uses content-box and overflows by 2×padding — which shows
      // up as the card being wider than the viewport (unequal left/right
      // margins, content shifted to one side). Prepend the minimal reset.
      const reset =
        "*,::before,::after{box-sizing:border-box;} body { margin: 0; padding: 0; background-color: #0f172a; }";
      const outPath = resolve(
        __dirname,
        "../../crates/blitz-quick-desktop/src/gen/bundle.css",
      );
      writeFileSync(outPath, `${reset}\n${css}`, "utf8");
      console.log(`[unocss] Wrote CSS to ${outPath}`);
    },
  };
}

export default defineConfig({
  plugins: [
    unocssSeparated(),
    solid({
      solid: {
        generate: "universal",
        moduleName: "@blitz-quick/solid-renderer",
      },
    }),
  ],
  resolve: {
    alias: {
      "@blitz-quick/solid-renderer": resolve(
        __dirname,
        "../../packages/solid-renderer/src/index.ts",
      ),
      "solid-js/web": resolve(
        __dirname,
        "../../packages/solid-renderer/src/index.ts",
      ),
    },
  },
  build: {
    lib: {
      entry: "src/index.tsx",
      formats: ["iife"],
      name: "BlitzJSApp",
      fileName: () => "bundle.js",
    },
    rollupOptions: {
      output: {
        inlineDynamicImports: true,
      },
    },
    outDir: "../../crates/blitz-quick-desktop/src/gen",
    emptyOutDir: false,
    minify: false,
  },
});
